imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            channels: ["!json_rpc"]
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  info
            channels: ["!json_rpc"]
        console:
            type:  console
        json_rpc:
            type:   stream
            path:   "%kernel.logs_dir%/json-rpc-%kernel.environment%.log"
            level:  info
            channels: ["json_rpc"]
        elasticsearch:
            type:   elasticsearch
            elasticsearch:
                host: localhost
            level: info
            channels: [app, json_rpc]